# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_users_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='hotel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='source',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='url',
            field=models.URLField(default='', max_length=300),
        ),
    ]
