# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20160502_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='hotel',
        ),
    ]
