# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_users_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=300)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Hotel')),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='PagUser',
        ),
    ]
