# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_hotelsuser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.CharField(default='', max_length=300),
        ),
    ]
