# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_hotel_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tipo',
            field=models.CharField(default='', max_length=300),
        ),
    ]
