# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_hotel_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Hotel')),
            ],
        ),
    ]
