# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hid',
            field=models.IntegerField(default=0),
        ),
    ]
