# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_image_hid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
