# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20160504_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='paguser',
            name='color',
            field=models.CharField(default='', max_length=300),
        ),
    ]
