# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_paguser_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='body',
            field=models.TextField(default='', max_length=800),
        ),
    ]
