# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_hotel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
