# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_comment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='number',
        ),
        migrations.AddField(
            model_name='hotel',
            name='numbercom',
            field=models.IntegerField(default=0),
        ),
    ]
