# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20160518_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
